### ISSUE TITLE
'ngInput' Dependency Injection error.

### ISSUE THREAD

**Issue by jimishio** [cesardeazevedo/ng-input#2]
Hello,
I have installed ngInput dependency in my angularJS project by "bower install ng-input" as per mentioned in ReadMe.md file.

I have injected dependency in my index.module.js by following:

angular.module('app',['something','something',...,'ngInput']);

<ng-input> tag is added with all the options mentioned in ReadMe.md file.
Example:
<ng-input theme='Ruri' icon='icon icon--fumi mdi mdi-account' class="input" type="text" label='First Name' color='#000'></ng-input>
<ng-input theme='Ruri' icon='icon icon--fumi mdi mdi-account' class="input" type="text" label='First'></ng-input>
<ng-input theme='Ruri' icon='icon icon--fumi mdi mdi-account' type="text" label='First Name' color='#000'></ng-input>

But when I run gulp serve, angular project is not getting started and error I am facing is : 
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ngInput due to:
Error: [$injector:nomod] Module 'ngInput' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.1/$injector/nomod?p0=ngInput

It seems like ngInput is not getting loaded. Please help.

**Comment by cesardeazevedo** [comment]
Hi, thanks for the feedback,

Have you included the script at page?
`<script src="bower_components/ng-input/dist/ng-input.min.js"></script>`

**Comment by jimishio** [comment]
Thanks for quick response. 

This is how I fixed my error:

put ng-input in your bower.json to install ng-input with other components.
bower.json:
"dependencies": {
.
.
.,
"ng-input":"~0.0.5"}

Now go to terminal and type below command to install ngInput as bower component:
bower install

Now go to your_app/bower_components/ng-input. open bower.json, and change main array as below:
"main": ["dist/ng-input.js", "dist/css/ng-input.css],

Include 'ngInput' in your angular modules:
angular.module('app',['some_modules',...,'ngInput']);

This solved my problem without adding any script file in my html file.

Thanks for this awesome repo @cesardeazevedo.

**Comment by cesardeazevedo** [comment]
You're right, the bower main files should be an array, my mistake, thanks for catch it.
I've pump the version to `0.0.6` to npm and bower.

Thank you.

**Comment by jimishio** [comment]
Thanks @cesardeazevedo
