### ISSUE TITLE
Animations for Theme "Chisato" Not Working in Mozilla

### ISSUE THREAD

**Issue by CarlsBad505** [cesardeazevedo/ng-input#5]
Animations not working properly for Chisato theme in the Mozilla Firefox browser. Can you please fix this issue?

**Comment by cesardeazevedo** [comment]
Thank you for report, i'll take a look

**Comment by CarlsBad505** [comment]
@cesardeazevedo Actually I solved it. I will create a pull request. Thank You!

**Comment by cesardeazevedo** [comment]
Awesome, pull requests are welcome...
